# https://taskfile.dev

version: '3'

env:
  MIGRATION_ROOT: "tools/migrations"
  SEED_ROOT: "tools/seeder"

tasks:
  setup:
    desc: "ローカル環境のセットアップを行う。(gitコマンドが使用できるようにする)"
    cmds:
      - cp {{.APP_ROOT}}/.gitconfig /root/.gitconfig
      - git config --global core.autocrlf input
      - git config --global --add safe.directory {{.APP_ROOT}}
      - chmod +x {{.APP_ROOT}}/.github/hooks/pre-commit
      - git config core.hooksPath {{.APP_ROOT}}/.github/hooks
      # わざわざコピーする理由は、commit時に毎回メアドとユーザー名の設定(.gitconfigの作成)を求められ面倒なので、git cloneするなら作成済みであろう.gitconfigを使うという魂胆である。
      # だが、Windowsユーザーが.gitconfigを使用中と解釈されるようでgit configコマンドが失敗するため、ファイルをコピーする必要がある。
      # core.autocrlf inputを使用する理由は、Linuxの改行コードが原因で差分が表示されてしまうため。
      # safe.directory $APP_ROOTを使用する理由は、WSL2側に配置しgitを使うには毎回求められるため。

  migration-drop:
    desc: "develop schema のテーブルを削除する。"
    cmds:
      - go run {{.MIGRATION_ROOT}}/main.go dev drop

  migration-create:
    desc: "develop schema のテーブル作成する。"
    cmds:
      - go run {{.MIGRATION_ROOT}}/main.go dev create

  migration-fresh:
    desc: "develop schema のテーブルを削除し作成する。"
    cmds:
      - task: migration-drop
      - task: migration-create

  migration-fresh-test:
    desc: "test schema のテーブルを削除し作成する。"
    cmds:
      - task: migration-test-drop
      - task: migration-test-create

  seed-dev:
    desc: "develop schema のテーブルにデータを投入する。"
    cmds:
      - go run {{.SEED_ROOT}}/main.go dev

  test:
    desc: "カバレッジ率を取得する。"
    cmds:
      - go test -tags=integration -cover -coverprofile=coverage.out ./...
      - go tool cover -html=coverage.out -o coverage.html
      - rm coverage.out